### DISCUSSION TITLE
WoW! But I need help ?

### DISCUSSION THREAD

**Discussion by R3nierjvr** [matt8707/ha-fusion#182] [Q&A]
Just wow been using your old dashboard....customized of course and love the new project.
Been staring at this for ours and figure out for the life of me how to add the plex now playing media card

**Comment by R3nierjvr** [comment]
Just an edit heres my config tried to add it in code... cameras show sidebar and main window but custom cards don't
```
views:
  - name: Home
    id: 2709303851432
    sections:
      - type: horizontal-stack
        sections:
          - name: Media
            items:
              - type: camera
                id: 3002686299612
                entity_id: camera.front_gate
                size: contain
              - type: custom:upcoming-media-card
                entity: sensor.plex_recently_added
                title: Recently Downloaded
                id: 3915537176268
            id: 2068403317209
        id: 8204650496391
  - name: Overview 2
    id: 2286602585377
    sections: []
sidebar:
  - type: camera
    id: 2264829598343
    entity_id: camera.front_gate
    size: contain
theme: muted
```

**Comment by R3nierjvr** [comment]
Hey mess around a bit and you figure it out , solved thx

**Reply by Andreasjkoch** [reply]
May I ask how you did it?

**Reply by R3nierjvr** [reply]
Sure :) Create a Horizontal Stack, add a Section I called it media then add the code under items:

```
items:
  - type: media
    id: 5276106620601
    conditional:
      - entity_id: sensor.plex_recently_added
        name: Last added
        icon: mdi:plex
        color: orange
        hold_action:
          action: more-info
      - entity_id: media_player.tv_samsung_7_series_55
      - entity_id: media_player.master_bedroom_speaker
      - entity_id: media_player.spotify_r3nierjvr
        icon: mdi:spotify
```

Also remeber that you have to setup and add the plex recently added sensor :)
[](https://github.com/custom-components/sensor.plex_recently_added)
