### DISCUSSION TITLE
How do i add Fusion as the default dashboard homepage in HA?

### DISCUSSION THREAD

**Discussion by Richiesh00ts** [matt8707/ha-fusion#412] [Q&A]
Hello all! i am looking for some help, so i can add Fusion to my default Homepage inside of HA.  When I attempt to add it inside of Dashboard, there is no option for me to do so. please help as I LOVE this dashboard and would like to make it my one and only default!

**Comment by LionCityGaming** [comment]
Use the new Webpage card on Home Assistant. Here's mine: 
![screenshot-1713102755877](https://github.com/matt8707/ha-fusion/assets/72677307/be7e4d9d-1ff1-46c3-9524-7ffa48c5ad63)

**Reply by al31c0** [reply]
Are you experiencing _ 401: Unauthorized!_ error at first load??

[image](https://github.com/matt8707/ha-fusion/assets/57990612/7eada569-25bc-43d7-8c08-23d2617d803e)

**Reply by LionCityGaming** [reply]
Is that on mobile/tablet? If it is, I've never tried it on mobile/tablet, as I have a seperate dashboard just for those.

**Reply by al31c0** [reply]
Yes is responsive so it works also for mobile. But the error appears everywhere at first load.

**Comment by gurglingtonic** [comment]
I found a solution for me to have Fusion as my default dashboard in HA. 

Solution requires 2 integrations via HACS:-
1. Ingress (https://github.com/lovelylain/hass_ingress)
2. Browser_mod

**Step 1:-**
For Ingress, include code below in your configuration.yaml

```
ingress:
  fusion:
    work_mode: hassio
    ui_mode: normal
    title: Fusion
    icon: mdi:view-dashboard
    url: 65f67727_ha_fusion
```

Code above allows me to customize url and hide header in mobile view. Restart HA after saving code.

**Step 2:-**
For Browser_mod, go to "Default dashboard". You can either edit "GLOBAL" for all users or "ADD USER SETTING" for specific user. For the value, manually type "fusion", it's not available in the dropdown menu. Press "OK" to save.

Refresh the page and you should see Fusion as your default page/dashboard.

**Reply by daywalkerb1** [reply]
Thank you very much for this. How do you not hide header in mobile view?

**Reply by gurglingtonic** [reply]
you may try this:-

```
ingress:
  fusion:
    work_mode: hassio
    ui_mode: toolbar
    title: Fusion
    icon: mdi:view-dashboard
    url: 65f67727_ha_fusion
```

or you may skip step 1 and proceed to step 2. manually type "65f67727_ha_fusion/ingress" instead of "fusion"

access fusion via the add-on "Show in sidebar"
