### DISCUSSION TITLE
Unable to configure long-lived access tokens

### DISCUSSION THREAD

**Discussion by ryandicenzo** [matt8707/ha-fusion#507] [Q&A]
Hey all!

I am trying to use ha-fusion with long-lived access tokens as when I try and access my fusion dashboard via the Home Assistant Companion App, it prompts me to do so (due to using ingress + app).

I have created a long-lived access token in HA, and included that in the ha-fusion tokens input box (pasted directly). However, after this is done ha-fusion loses the ability to connect to my HA and none of the entities load. In network tab, I see web socket requests.

<img width="579" alt="Screenshot 2024-06-23 at 12 48 13 PM" src="https://github.com/matt8707/ha-fusion/assets/14367186/dd314a7d-185f-44ea-ab3b-1a6faee66879">

From here, the question is: am I configuring something incorrectly with my access tokens? Is it expected that the app breaks when access token is set and user attempts to load directly?

I spent time attempting to configure the long-term auth tokens with ingress, but I'm not sure if this is the right approach. In case it's relevant, I'm using Home Assistant Cloud with Nabu for external access and running HA via containers.

ingress config:

```
ingress:
  fusion:
    title: Home
    ui_mode: toolbar
    icon: mdi:lightning-bolt
    url: http://<local-ip>:5050
    // Tried with and without below, and in some other formats
    headers: 
      authorization: <auth-token>
```

Am I missing something basic with the access tokens?

Without the tokens I can load the fusion dashboard via my external HA url via WebBrowser, it's just that I can't load it with the app.
