### ISSUE TITLE
Time out setting

### ISSUE THREAD

**Issue by Lancealot1990** [matt8707/ha-fusion#138]
Hi Matt,

I think having a button time out would be good, for example if I click on a light to dim it down and walk away the dimmer slider would still be present until I press exit or on the screen somewhere.

let me know your thoughts 

thanks 
L

**Comment by matt8707** [comment]
The first thought that comes to mind is to listen for a special event. This way you can set you own conditions

```yaml

automation:
  - alias: close ha-fusion popup
    trigger:
      - platform: state
        entity_id: light.hall
        from: "on"
        to: "off"
    action:
      - event: HA_FUSION
        event_data:
          event: close_popup
```
