### ISSUE TITLE
RGB Controls

### ISSUE THREAD

**Issue by Harti33** [matt8707/ha-fusion#18]
Hi,
unfortunately you can only change the temperature of the Shelly RGBW2 Relay and not the colour.

Current version: 2023.12.7

**Comment by matt8707** [comment]
Can you post attributes yaml, for example this is what a hue bulb looks like

```yaml
min_color_temp_kelvin: 2000
max_color_temp_kelvin: 6535
min_mireds: 153
max_mireds: 500
supported_color_modes:
  - color_temp
  - xy
color_mode: color_temp
brightness: 255
color_temp_kelvin: 3125
color_temp: 320
hs_color:
  - 27.631
  - 53.602
rgb_color:
  - 255
  - 181
  - 118
xy_color:
  - 0.485
  - 0.381
mode: normal
dynamics: none
friendly_name: Datorlampa
supported_features: 40

```
