### ISSUE TITLE
Save button not working

### ISSUE THREAD

**Issue by garrettisrael** [matt8707/ha-fusion#19]
Installed with docker compose. Console throws this error when I click the save button.

![image](https://github.com/matt8707/ha-fusion/assets/40127180/7123b2e4-50e1-47d9-9046-c5c8f07e4ecd)

**Comment by matt8707** [comment]
can't replicate, have you set a volume?

```yaml
version: '3'
services:
  ha-fusion:
    container_name: ha-fusion
    image: ghcr.io/matt8707/ha-fusion
    volumes:
      - /path/to/ha-fusion:/app/data
    network_mode: bridge
    ports:
      - 5050:5050
    environment:
      TZ: Europe/Stockholm
      HASS_URL: http://192.168.1.241:8123
    restart: always

```
