### ISSUE TITLE
FR: Custom popups

### ISSUE THREAD

**Issue by anarion80** [matt8707/ha-fusion#25]
Hello! First of all - great work on this new approach! My Amazon Fire 10 tablet is now usable, while with the previous hass-config dashboard it struggled a lot with all the heavy client-side JS.

Perhaps you are already thinking on popups, but I would like to formally request that ability. For example to be able to click on the weather type item in the sidebar:
![obraz](https://github.com/matt8707/ha-fusion/assets/2185791/4b73e350-f940-4681-a656-b06b7fbf4d67)
to have a popup open with more detailed weather view.

Perhaps something like this:

```yaml
- type: weather
    entity_id: weather.openweathermap
    weather_sensor: sensor.openweathermap_weather
    extra_sensor: sensor.openweathermap_forecast_precipitation_probability
    extra_sensor_icon: mdi:drop
    icon_pack: meteocons
    popup: weather
```

The popup could use exactly the same mechanics as views and be defined in dashboard.yaml:

```yaml
popups:
  - name: Weather
    id: 6467602449648
    sections:
      - type: horizontal-stack
        id: 5078078976670
        sections:
          - name: Main
            id: 2171067078835
            items:
              - type: button
                entity_id: sensor.ventilation_info
                id: 5008685947164
                name: Rekuperacja
                icon: mdi:fan
...
```

Potentially applicable to any button/item in the dashboard.
