### ISSUE TITLE
Empty template values shown as unknown

### ISSUE THREAD

**Issue by anarion80** [matt8707/ha-fusion#26]
I'm trying to move your former hass-config dashboard to this new one. Previously we had the sidebar in one template sensor with attributes for greet, weather, vacuum, laundry, etc.

With the new one, using the same sensor & attributes, the elements that are empty and were not displayed in the former dashboard, are now shown as unknown:

![obraz](https://github.com/matt8707/ha-fusion/assets/2185791/d1356c8d-03d7-4ca9-b7ed-2cd1479ca6d7)

This is using the following dashbaord items:

```yaml
- type: template
    template: '{{ states[''sensor.template_sidebar''].attributes.active }}'
    id: 2790676343774
  - type: template
    template: '{{ states[''sensor.template_sidebar''].attributes.open }}'
    id: 2790676343775
  - type: template
    template: '{{ states[''sensor.template_sidebar''].attributes.laundry }}'
    id: 2790676343776
  - type: template
    template: '{{ states[''sensor.template_sidebar''].attributes.vacuum }}'
    id: 2790676343773
```

with `laundry' and `vacuum` attributes being shown as empty by HA:
![obraz](https://github.com/matt8707/ha-fusion/assets/2185791/70dcb119-51d6-438a-9bbc-8b686a064e7a)

and I would expect them to be empty (not shown) here as well.
