### ISSUE TITLE
Windwos Sensor

### ISSUE THREAD

**Issue by dos1973** [matt8707/ha-fusion#263]
Hi, 

i have Homematic Window Sensor
following entities are available `options: closed, tilted, open`

fusion shows the current windows state in "german- language" for closed and open correct, 
but `tilted` is missing, there is no translation - just shows `tilted`.

- can you please add for the entities `tilted` = Gekippt
- is it possible to add addional color icon values for each state?

- when the windows sensor is in state `open` the whole Button shows active (white)
- is it possible to activate the Button also when the sensor value is `tilted`

Thanks in advance

***
Link to HmIP-SRH
[https://de.elv.com/elv-homematic-ip-arr-bausatz-fenstergriffsensor-hmip-srh-fuer-smart-home-hausautomation-152133?utm_source=google&utm_medium=cpc&utm_campaign=perfmax_shopping_de&refid=Gads&Gads_PerfMax_Shopping&gad_source=1&gclid=CjwKCAiA5L2tBhBTEiwAdSxJX65f-Dile1gipC8-VTrLVGoeqkPjcpCYMlINlq2KYEJnyIEE-a5MrRoCbbwQAvD_BwE&dt_dynco=0714FA3244CAB1A58C5572A19677C66E](HmIP-SRH)

**Comment by matt8707** [comment]
Yes I will look up translation key for 'tilted'

I'm interested in attribute data from dev tools, can you post that for your sensor?

For example

```yaml
state_class: measurement
battery_state: normal
unit_of_measurement: "%"
device_class: battery
friendly_name: Badrum Dimmer Batteri

```
