### ISSUE TITLE
[Bug] Map Tiler doesn't work anymore (Person)

### ISSUE THREAD

**Issue by RubenDijk** [matt8707/ha-fusion#310]
when I press the button the popup loads earlier a location map was visible here (the MapTiler) this now does not come up anymore

Info:
Google Chrome browser on pc and phone + Fully Kiosk Browser
Unraid Docker: ha-fusion
Version: 2024.1.10

configuration.yaml:
```yaml
locale: nl
addons:
  maptiler:
    apikey: xxxxxxxxxxxxxxxxxx
```

![image](https://github.com/matt8707/ha-fusion/assets/18540436/fa208ccd-ca3e-4414-a835-b05a2f597cc6)
![image](https://github.com/matt8707/ha-fusion/assets/18540436/fd07791d-42aa-48fd-8626-e3df741dc131)
