### ISSUE TITLE
Energy view

### ISSUE THREAD

**Issue by randykramer07** [matt8707/ha-fusion#379]
It would be nice to have a view option for energy.

Including:
- Consumption
- Production
- Solar Energy

- Maybe therefore the lovelace one is usuable (like the power flow card from HACS)

**Comment by matt8707** [comment]
This is super low priority, since I don't use the energy view myself, I don't have the setup or context needed to develop or test against it.

**Comment by tomaslikar** [comment]
I think do this in the current version using a browser-mod popup. Here is an example to use a service:
`                  service: |-
                    service: browser_mod.popup
                    target:
                      entity_id: binary_sensor.tablet_test
                    data:
                      dismissable: true
                      title: Energy State
                      autoclose: false
                      content:
                        type: vertical-stack
                        cards:
                          - type: energy-distribution
                            aspect_ratio: 50%
                      size: wide
                      style: |2-
                          --popup-min-width: 40vw;
                          --popup-max-width: 600px;
                          --popup-border-radius: 10px;
                          --popup-padding-x: 10px;
                          --popup-padding-y: 10px;
                          --dialog-backdrop-filter: blur(0.5em) brightness(0.75);`

<img width="1194" alt="image" src="https://github.com/matt8707/ha-fusion/assets/67967603/4620eeb1-72f3-4dec-b737-f10570784875">

**Comment by pimp1310** [comment]
> I think you can do this in the current version using a browser-mod popup. Here is an example to use a service:
> 
> ```
>                 service: |-
>                 service: browser_mod.popup
>                 target:
>                   entity_id: binary_sensor.tablet_test
>                 data:
>                   dismissable: true
>                   title: Energy State
>                   autoclose: false
>                   content:
>                     type: vertical-stack
>                     cards:
>                       - type: energy-distribution
>                         aspect_ratio: 50%
>                   size: wide
>                   style: |2-
>                       --popup-min-width: 40vw;
>                       --popup-max-width: 600px;
>                       --popup-border-radius: 10px;
>                       --popup-padding-x: 10px;
>                       --popup-padding-y: 10px;
>                       --dialog-backdrop-filter: blur(0.5em) brightness(0.75);
> ```
> 
> <img alt="image" width="1194" src="https://private-user-images.githubusercontent.com/67967603/307129648-4620eeb1-72f3-4dec-b737-f10570784875.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3MjE5NTcsIm5iZiI6MTcwODcyMTY1NywicGF0aCI6Ii82Nzk2NzYwMy8zMDcxMjk2NDgtNDYyMGVlYjEtNzJmMy00ZGVjLWI3MzctZjEwNTcwNzg0ODc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDIwNTQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhNDYyYjkzOWE4Y2EwNzk1ZTdmMDI5ZjI4MzI0YjE3NjhlM2M1OWRmN2ZjZjdhMDNkN2QzNjJkMzFhMmYzMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6ikdPN2QkW7unzKVAikpTeNqrbUgoyXkVAzO3GtJbnA">



thats the best hint i ever get!!!

now its possible to show custom popups in Fusion, here light groups and devices with low batteries

![group_light](https://github.com/matt8707/ha-fusion/assets/6306057/4d941d79-7fd4-473d-ac08-8b694f607fac)

![low_battery](https://github.com/matt8707/ha-fusion/assets/6306057/0a95c825-2cb3-4d54-9497-1271099c5f81)

**Comment by fastxl2024** [comment]
@tomaslikar What is your config for this? I can't fix it.

**Comment by anonymousaxx** [comment]
@tomaslikar @pimp1310 your code is not working, do I have to consider anything?

I have the browser_mod service and used it successfully with Matt's first dashboard layout. Adding your code to the service field (or via code editor) still shows the standard light pop-up instead of the browser_mod pop-up. Any help is appreciated.

**Comment by tomaslikar** [comment]
Make sure to disable “Show more info” in the Fusion button configuration

**Comment by jonasjeeliasson** [comment]
@tomaslikar I'm trying it out as well but nothing happens. Do you need to specify the target.entity_id and what value should it then have?

**Comment by jonasjeeliasson** [comment]
> @tomaslikar I'm trying it out as well but nothing happens. Do you need to specify the target.entity_id and what value should it then have?
> 
> I tried this:
> 
> ```
> - id: 4763180828941
>   type: button
>   entity_id: media_player.kok_hub
>   template:
>     service: |-
>       service: browser_mod.popup
>       data: 
>         title: Testar
>         content: Hello
>   more_info: false
> ```

Tried registering the device in browser_mod as well and using one of the binary sensors that was created for it but with no luck:

```

- id: 1933934625909
  type: button
  entity_id: media_player.kok_hub
  template:
    service: |-
      service: browser_mod.popup
      target:
        entity_id: binary_sensor.mbp_arc
      data: 
        title: Testar
        content: Hello
  more_info: false
```

**Comment by matt8707** [comment]
Just to clarify, browser_mod.popup is not supported in ha-fusion and only works in home assistant frontend, not when exposing port with addon and not when using docker. Discussion https://community.home-assistant.io/t/browser-mod-turn-your-browser-into-a-controllable-device-and-a-media-player/123806/1

**Comment by jonasjeeliasson** [comment]
Aha, maybe I misunderstood then, looked like the screenshot showed ha-fusion in the background with browser_mod popups. I've already have browser_mod setup and use it heavily in my normal dashboard (which is heavily inspired by Matt's previous nice dashboard :)). But there I use it with the fire-event thingy, but also trying out the service call both of these work (i.e with and without the target):

```
type: button
name: Test button
tap_action:
  action: call-service
  service: browser_mod.popup
  data:
    title: test
    content: test
```
    
and

```
type: button
name: Test button
tap_action:
  action: call-service
  service: browser_mod.popup
  target:
    entity_id: binary_sensor.mbp_arc
  data:
    title: test
    content: test
```

It would just have been a nice to have until ha-fusion is more prime time ready. I could have put some of the stuff that is missing in these popups in the mean time :) 

Other than that, great work! I'll have a beta dashboard with fusion running on the side to follow along with your progress!

**Comment by jonasjeeliasson** [comment]
Got it working, now I think I understood what you said with "only works in home assistant frontend" :) When I run it through my normal HA frontend (and not through http://url:8099) the popups work!

I.e this works:

```
- id: 1933934625909
  type: button
  entity_id: media_player.kok_hub
  template:
    service: |-
      service: browser_mod.popup
      data: 
        title: Testar
        content: Hello
```
