### ISSUE TITLE
Service Support: Input Select Next

### ISSUE THREAD

**Issue by stephenmetts** [matt8707/ha-fusion#395]
First, major praise for developing and sharing such an awesome tool.  I enjoy being an early adopter, and putting it through its paces.

I believe I've found an issue (and if it's user error, would appreciate a correction).  As a user, I'd like to have a Button change the state of an input select using the input select next service.

I've attempting numerous iterations of this in the Button component Service, but it appears to never successfully make the call.  When attempting the yaml below in OOTB HASS Developer tools, it works without issue.

`service: input_select.select_next
target:
  entity_id:
    - input_select.lock_status
data:
  cycle: true
`

**Comment by matt8707** [comment]
The issue here is that `target` is not supported yet, you can put entity_id in data

```yaml
service: input_select.select_next
data:
  entity_id: input_select.lock_status
  cycle: true
```
