### ISSUE TITLE
ERR_CANNOT_CONNECT - fresh addon setup

### ISSUE THREAD

**Issue by kramttocs** [matt8707/ha-fusion#46]
Is there some configuration that needs to be done that I am not aware of?
Installed the addon and with the latest version it now loads the UI but in the bottom left I get the error above.
I do see in the AddOn logs these messages:

Starting Fusion...
listening on port 5050
env HASS_URL undefined
env ADDON true
No existing file found for ./data/configuration.yaml
No existing file found for ./data/dashboard.yaml

**Comment by gladrun** [comment]
I am getting the same in the logs. There is no new folder created in the custom_components. I have installed using the addon method.

**Comment by WeterPeter** [comment]
I get this message on my desktop (Mac Studio) with Firefox.
On my Macbook with also Firefox it works however.
I deleted cookies on the desktop but to no avail.

**Comment by matt8707** [comment]
I need more info

**Comment by kramttocs** [comment]
I just updated to the latest and it's working now (no error and my devices are showing).
Thanks!

**Comment by andromidasj** [comment]
Don't think this should've been closed... I'm trying to set up ha-fusion with Docker and keep getting this same error:

![CleanShot 2024-01-16 at 10 34 51@2x](https://github.com/matt8707/ha-fusion/assets/66661368/06164621-8653-4779-85de-58dd3d4d6c04)
Here are my docker logs:
```
2024-01-16T16:34:02.989324248Z [HPM] Proxy created: /  -> http://192.168.1.101:8123
2024-01-16T16:34:02.994219570Z listening on port 5050
2024-01-16T16:34:02.994369608Z env HASS_URL http://192.168.1.101:8123
2024-01-16T16:34:02.994478011Z env ADDON false
2024-01-16T16:34:40.380370860Z No existing file found for ./data/configuration.yaml
2024-01-16T16:34:40.380565268Z No existing file found for ./data/dashboard.yaml
2024-01-16T16:34:46.329289740Z No existing file found for ./data/configuration.yaml
2024-01-16T16:34:46.329467309Z No existing file found for ./data/dashboard.yaml
```

Here's my docker-compose file:
```yml
  ha-fusion:
    container_name: ha-fusion
    image: ghcr.io/matt8707/ha-fusion
    volumes:
      - ${DOCKER_PATH}/ha-fusion:/app/data
    network_mode: bridge
    ports:
      - 5050:5050
    environment:
      TZ: ${TZ}
      HASS_URL: http://192.168.1.101:8123
    restart: always
```

I checked the permissions for the app directory on my host, and made sure that I have read-write access.

```
josh@myserver:~/docker/ha-fusion$ ll
total 8
drwxr-xr-x  2 josh josh 4096 Jan 16 10:33 ./
drwxrwxrwx 48 josh josh 4096 Jan 16 10:22 ../
```

Am I missing anything? I tried manually copying the example configuration and dashboard files from the GitHub repo into that app directory and restarting the container, but I still get a `ERR_CANNOT_CONNECT` error. (Logging in to the Home Assistant login screen on app startup worked without an issue.)
