### ISSUE TITLE
Weather forecast still disappears sometimes

### ISSUE THREAD

**Issue by anarion80** [matt8707/ha-fusion#478]
The weather forecast still disappears sometimes after refresh. When it disappears I can see the following log on the console:

![image](https://github.com/matt8707/ha-fusion/assets/2185791/1d6e3e2a-214e-428b-991b-738267370f8d)

This is with the following dashboard snippet:

```yaml
  - type: weather
    entity_id: weather.openweathermap
    weather_sensor: sensor.openweathermap_weather
    extra_sensor: sensor.openweathermap_forecast_precipitation_probability
    extra_sensor_icon: mdi:drop
    show_apparent: true
    icon_pack: meteocons
    id: 2790676343766
  - id: 2687656384157
    type: weather_forecast
    entity_id: weather.openweathermap
    days_to_show: 4
    icon_pack: meteocons
```
