### ISSUE TITLE
Adding a different state at conditional media

### ISSUE THREAD

**Issue by Kaspermaat** [matt8707/ha-fusion#498]
Hi Matt,

First of all, I want to thank you for the great work! Your old dashboard has been hanging on the wall for over a year now. I'm following this new project with great interest. Currently, I'm using a "Latest News" feature on the dashboard. This is an image I added using a Genetic Camera. However, I'd like the news title, which is in a different sensor, to be displayed as the title. In summary, it would be great if you could set a different sensor for the title in the conditional media settings.
It also would me nice to change the icon as well.  ;)

![IMG_0012](https://github.com/matt8707/ha-fusion/assets/58333104/f2f11e40-d6b1-4212-ae35-52e21d6a1807)

**Comment by matt8707** [comment]
Hi, this is not what it's designed to do, but you can make your own template sensor as a workaround.

```yaml
template:
  - sensor:
      - unique_id: latest_news
        state: >
          {{ states('sensor.news') }}
        attributes:
          friendly_name: Latest news
          icon: mdi:newspaper
          entity_picture: /local/news.png

```
