### ISSUE TITLE
Save button does nothing

### ISSUE THREAD

**Issue by paulmorabito** [matt8707/ha-fusion#534]
Hi, I'm using the latest version as an add-on on 2024.7.3 of Home Assistant (HassOS). The issue I am facing is the save button is not working. 

Is there any further info I can provide you to further trouble shoot?

**Comment by matt8707** [comment]
Hi, yes, addon logs and browser console logs

**Comment by paulmorabito** [comment]
Here you go:

[js.log](https://github.com/user-attachments/files/16337430/js.log)

Add-on logs:

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Starting Fusion...
ADDON: true
INGRESS_PORT: 8099
EXPOSED_PORT: 
HASS_PORT: 8123

**Comment by matt8707** [comment]
Thanks, in js.log i see

```js
CodeConfig.CxOcBhK1.js:1 Y {name: 'YAMLException', reason: 'can not read a block mapping entry; a multiline key may not be an implicit key', mark: {…}, message: 'can not read a block mapping entry; a multiline ke… 12 | ffff\n 13 | \n 14 | theme: godis\n-----------^', stack: 'YAMLException: can not read a block mapping entry;…p/immutable/chunks/CodeConfig.CxOcBhK1.js:1:5418)'}
```

I think you're trying to save invalid yaml in code editor

**Comment by paulmorabito** [comment]
Yeah I pasted the element incorrectly but the last attempt had valid yml.

**Comment by matt8707** [comment]
Can you post your yaml like this

````
```yaml
theme: godis
```
````

**Comment by paulmorabito** [comment]
Here it is. i've just installed it and am trying to get to grips with how it worked so added an entity to the yaml. There are no config errors reported in the editor.

```
views:
  - id: 1896633189085
    type: configure
    name: Overview
  - name: Climate
    id: 995548803567
    sections:
      - type: horizontal-stack
        sections: []
        id: 6196183727261
  - type: entity
    entity: binary_sensor.hue_secure_contact_sensor_1_opening
    icon: mdi:door
    name: Entrance
sidebar: []
theme: godis
```
