### ISSUE TITLE
sidebar graph not possible to use self created sensors

### ISSUE THREAD

**Issue by canedje** [matt8707/ha-fusion#89]
I do make a lot off self defined sensors for example:

```
power_consumption_watt:
      friendly_name: "Power Consumption Watt"
      unit_of_measurement: "W"
      icon_template: "mdi:flash"
      value_template: "{{ ((states('sensor.dsmr_reading_electricity_currently_delivered') | float * 1000) - (states('sensor.dsmr_reading_electricity_currently_returned') | float * 1000)) }}"
```
The self created "power_consumption_watt" sensor is not selectable in the graph tile
